name: Init

runs:
  using: 'composite'

  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v5
      with:
        version: 10
        run_install: false

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: './.node-version'
        cache: 'pnpm'

    - name: Setup Git Config
      shell: bash
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Fetch Deps
      shell: bash
      run: pnpm install --frozen-lockfile
